name: todolist
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
 # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.15.1 <3.0.0"


dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  faker: ^2.0.0
  provider: ^6.0.2
  dio: ^4.0.4
  http: ^0.13.4

dev_dependencies:
  flutter_native_splash: ^1.3.2
  flutter_launcher_icons: "^0.9.2"
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/
  uses-material-design: true
  fonts:
      - family: ShadowsIntoLight
        fonts:
          - asset: assets/fonts/ShadowsIntoLight-Regular.ttf
            style: italic

flutter_icons:
  image_path: "assets/icon/icon.png"
  android: "launcher_icon"
  ios: true
  adaptive_icon_background: "#006064"
  adaptive_icon_foreground: "assets/icon/icon.png"

flutter_native_splash:
  color: "#006064"
  image: assets/splashscreen/icon.png
